language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - >
    INSTALL_ETCD=2.1.1
    EXTRA_ETCD="[etcd]"
  - EXTRA_ETCD=""

install: pip install -e .${EXTRA_ETCD}

script:
  - coverage run --source=pyconfig setup.py test

before_script:
  - >
    if [ -n "$INSTALL_ETCD" ]; then
      curl -L  https://github.com/coreos/etcd/releases/download/v${INSTALL_ETCD}/etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz -o etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz &&
      tar xzvf etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz &&
      cd etcd-v${INSTALL_ETCD}-linux-amd64 &&
      ./etcd --version &&
      ./etcd & &&
      cd -
    fi
  - pip install nose mock coverage coveralls

after_success:
  - coveralls
