language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - INSTALL_ETCD="[etcd]"
  - INSTALL_ETCD=""

install: pip install -e .${INSTALL_ETCD}

script:
  - coverage run --source=pyconfig setup.py test

before_script:
  - pip install nose mock coverage coveralls

after_success:
  - coveralls
