language: python
sudo: false

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - >
    _SSL="`pwd`/test/ssl"
    INSTALL_ETCD=2.1.1
    EXTRA_ETCD="[etcd]"
    ETCD_TRUSTED_CA_FILE="${_SSL}/cacert.pem"
    ETCD_CERT_FILE="${_SSL}/server.crt"
    ETCD_KEY_FILE="{$_SSL}/server.key"
    ETCD_ADVERTISE_CLIENT_URLS="https://127.0.0.1:2379"
    ETCD_LISTEN_CLIENT_URLS="https://127.0.0.1:2379"
    PYCONFIG_ETCD_HOSTS="127.0.0.1:2379"
  - >
    INSTALL_ETCD=2.1.1
    EXTRA_ETCD="[etcd]"
    PYCONFIG_ETCD_HOSTS="127.0.0.1:2379"
  - >
    INSTALL_ETCD=2.1.1
    EXTRA_ETCD=""

install: pip install -e .${EXTRA_ETCD}

script:
  - coverage run --source=pyconfig setup.py test

before_script:
  - curl -L  https://github.com/coreos/etcd/releases/download/v${INSTALL_ETCD}/etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz -o etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz
  - tar xzvf etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz
  - cd etcd-v${INSTALL_ETCD}-linux-amd64
  - ./etcd --version
  - ./etcd &
  - cd -
  - pip install nose mock coverage coveralls

after_success:
  - coveralls
